version: '3'

services:
  soulseek:
    image: realies/soulseek
    container_name: soulseek
    env_file: soulseek.env
    ports:
      - 6080:6080
    volumes:
      - ./data:/data/.SoulseekQt
      - ./logs:/data/Soulseek Chat Logs
      - /downloads:/root/Soulseek Downloads
      - ./uploads:/data/uploads
    restart: unless-stopped
