version: '3'

services:
  soulseek:
    image: realies/soulseek:latest
    container_name: soulseek
    env_file: soulseek.env
    ports:
      - 6080:6080
    volumes:
      - ./data:/root/.SoulseekQt
      - /logs:/root/Soulseek Chat Logs
      - /downloads:/root/Soulseek Downloads
      - /uploads:/root/uploads
    restart: unless-stopped
