services:
  spotify_ripper:
    image: thibmaek/spotify-ripper
    container_name: spotify_ripper
    env_file: spotify_ripper.env
    volumes:
      - ./config.ini:/root/.spotify-ripper/config.ini
      - ./playlist.txt:/root/playlist.txt
      - ./logs:/logs
      - ./downloads:/data
    tty: true
    restart: unless-stopped
