version: '3'

services:
  heimdall:
    image: ghcr.io/ajnart/homarr
    container_name: homarr
    env_file: homarr.env
    ports:
      - 7575:7575
    volumes:
      - ./config:/app/data/configs
      - ./icons:/app/public/icons
      - ./images:/app/public/img
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
