version: '3'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    env_file: heimdall.env
    ports:
      - 8080:80
    volumes:
      - ./config:/config
    restart: unless-stopped
