version: '3'

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    env_file: tautulli.env
    ports:
      - 8181:8181
    volumes:
      - ./config:/config
      - /plex/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    restart: unless-stopped

  tautulli_prometheus_exporter:
    image: ghcr.io/amalgamated-tools/tautulli-exporter/tautulli-exporter
    container_name: tautulli_prometheus_exporter
    env_file: tautulli_prometheus_exporter.env
    ports:
      - 9487:9487
    restart: unless-stopped
