repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
        exclude: .vscode

  - repo: https://github.com/thibmaek/pre-commit
    rev: v1.0.1
    hooks:
      - id: disallow-yml
        exclude: ^(files/docker_compose/)
      - id: shellcheck

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
        files: docker-compose.yaml$

  - repo: local
    hooks:
      - id: yamllint
        name: Lint YAML
        entry: yamllint
        language: system
        files: \.(yaml|yml)$
