- set_fact:
    bat_version: 0.17.1

- debug:
    msg: |
      Package `bat@{{ bat_version }}` is unavailable from the main repository.
      Its relevant .deb package will be downloaded.

      In the future, please migrate to a version of bat in the main apt repository

- name: "Download bat dependencies"
  become: true
  apt:
    name:
      - libgcc1-armhf-cross
      - gcc-8-cross-base
      - libc6-armhf-cross

- name: "Download bat (amd64)"
  when: "not 'arm' in ansible_architecture"
  get_url:
    url: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_amd64.deb"
    dest: "/tmp/bat_{{ bat_version }}.deb"
    mode: 0755

- name: "Download bat (armhf)"
  when: "'arm' in ansible_architecture"
  get_url:
    url: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_armhf.deb"
    dest: "/tmp/bat_{{ bat_version }}.deb"
    mode: 0755

- name: "Install bat"
  when: "'arm' in ansible_architecture"
  become: true
  shell: dpkg -i /tmp/bat_{{ bat_version }}.deb
