version: '3'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    env_file: sonarr.env
    ports:
      - 8989:8989
    volumes:
      - ./config:/config
      - /tv:/tv
      - /downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  sonarr_exporter:
    image: ghcr.io/onedr0p/exportarr
    container_name: sonarr_exporter
    env_file: sonarr_exporter.env
    ports:
      - 9707:9707
    command: ['sonarr']
    restart: unless-stopped
