# Ref: https://blog.r0b.io/post/minimal-rpi-kiosk/
# This playbook is meant to be ran against a Lite install (headless/no desktop GUI)
---
- name: 'Raspberry Pi Kiosk'

  hosts: rpi

  tasks:
    - name: 'Upgrade apt packages'
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: true

    - name: 'Install required packages'
      become: true
      ansible.builtin.apt:
        name:
          - chromium-browser
          - unclutter
          - x11-xserver-utils
          - xdotool
          - xinit
          - xserver-xorg-core
          - xserver-xorg-input-all
          - xserver-xorg-video-all

    - name: 'Auto-boot to console (logged in)'
      block:
        - name: 'Set default target to multi-user'
          become: true
          register: systemd_default
          changed_when: '"Creating symlink" in systemd_default.rc'
          ansible.builtin.command: 'systemctl set-default multi-user.target'
        - name: 'Symlink default getty service to drop-in'
          become: true
          ansible.builtin.file:
            src: '/lib/systemd/system/getty@.service'
            dest: '/etc/systemd/system/getty.target.wants/getty@tty1.service'
            state: link
        - name: 'Ensure autologin in drop-in service'
          ansible.builtin.blockinfile:
            path: '/etc/systemd/system/getty@tty1.service.d/autologin.conf'
            block: |
              [Service]
              ExecStart=
              ExecStart=-/sbin/agetty --autologin {{ main_user }} --noclear %I \$TERM
              EOF

    - name: 'Auto-start X Server'
      ansible.builtin.blockinfile:
        create: true
        path: '{{ ansible_env.HOME }}/.bash_profile'
        mode: 0644
        block: |
          if [ -z "$DISPLAY" ] && [ $(tty) = /dev/tty1 ]; then
            startx
          fi

    - name: "Check if Ansible var 'kiosk_url' is set"
      when: kiosk_url is undefined
      ansible.builtin.meta: end_host

    - name: 'Auto-start Chromium when starting X Server'
      ansible.builtin.blockinfile:
        create: true
        path: "{{ ansible_env.HOME }}/.xinitrc"
        mode: 0644
        block: |
          #!/usr/bin/env sh
          xset -dpms
          xset s off
          xset s noblank

          unclutter &
          chromium-browser {{ kiosk_url }} \
            --start-fullscreen \
            --kiosk \
            --noerrdialogs \
            --disable-translate \
            --no-first-run \
            --fast \
            --fast-start \
            --disable-infobars \
            --disable-features=TranslateUI \
            --disk-cache-dir=/dev/null \
            --overscroll-history-navigation=0 \
            --disable-pinch

    - name: 'Reboot'
      ansible.builtin.reboot:
        msg: 'Reboot initiated by Ansible'
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
