---
- name: 'Add Node.js plugin'
  register: asdf_add_node
  changed_when: '"already added" not in asdf_add_node.stderr'
  failed_when:
    - asdf_add_node.rc != 0
    - '"already added" not in asdf_add_node.stderr'
  ansible.builtin.command: 'asdf plugin add nodejs'

- name: 'Copy default NPM packages file'
  ansible.builtin.copy:
    src: 'files/.default-npm-packages'
    dest: '{{ ansible_env.HOME }}/.default-npm-packages'
    mode: 0644

- name: 'Install Node.js'
  register: asdf_install_node
  changed_when: '"is already installed" not in asdf_install_node.stdout'
  failed_when:
    - asdf_install_node.rc != 0
    - '"is already installed" not in asdf_install_node.stderr'
  ansible.builtin.command: 'asdf install nodejs latest:{{ asdf_lts_versions.nodejs }}'

- name: 'Set global Node.js version'
  changed_when: true
  ansible.builtin.command: 'asdf global nodejs latest:{{ asdf_lts_versions.nodejs }}'
