- name: 'Add ruby plugin'
  register: asdf_add_ruby
  changed_when: '"already added" not in asdf_add_ruby.stderr'
  failed_when:
    - asdf_add_ruby.rc != 0
    - '"already added" not in asdf_add_ruby.stderr'
  ansible.builtin.command: 'asdf plugin add ruby'

- name: 'Install latest ruby {{ asdf_lts_versions.ruby }}'
  register: asdf_ruby_install
  changed_when: '"already added" not in asdf_ruby_install.stdout'
  failed_when:
    - asdf_ruby_install.rc != 0
    - '"already added" not in asdf_ruby_install.stderr'
  ansible.builtin.command: 'asdf install ruby latest:{{ asdf_lts_versions.ruby }}'

- name: 'Set global to ruby@{{ ruby_latest.stdout }}'
  changed_when: true
  ansible.builtin.command: 'asdf global ruby latest:{{ asdf_lts_versions.ruby }}'

- name: 'Install additional ruby version'
  when: ruby_versions is defined and (ruby_versions | length > 0)
  ansible.builtin.command: 'asdf install ruby {{ item }}'
  loop: '{{ ruby_versions }}'
