- name: 'Add Ruby plugin'
  register: asdf_add_ruby
  changed_when: '"already added" not in asdf_add_ruby.stderr'
  failed_when:
    - asdf_add_ruby.rc != 0
    - '"already added" not in asdf_add_ruby.stderr'
  ansible.builtin.command: 'asdf plugin add ruby'

- name: 'Copy default Ruby gems file'
  ansible.builtin.copy:
    src: 'files/.default_gems'
    dest: '{{ ansible_env.HOME }}/.default_gems'
    mode: 0644

- name: 'Install Ruby'
  register: asdf_ruby_install
  changed_when: '"is already installed" not in asdf_ruby_install.stdout'
  failed_when:
    - asdf_ruby_install.rc != 0
    - '"already installed" not in asdf_ruby_install.stderr'
  ansible.builtin.command: 'asdf install ruby latest:{{ asdf_lts_versions.ruby }}'

- name: 'Set global Ruby version'
  changed_when: true
  ansible.builtin.command: 'asdf global ruby latest:{{ asdf_lts_versions.ruby }}'
