---
- name: 'Get the hostname'
  register: motd_hostname
  command: hostname
  changed_when: false

- name: 'Remove default MOTD'
  become: true
  file:
    path: /etc/motd
    state: absent

- name: 'Generate MOTD via cfonts'
  delegate_to: localhost
  command: cfonts {{ motd_hostname.stdout }} -f simple3d
  changed_when: false
  register: motd_content

- name: 'Copy MOTD'
  become: true
  copy:
    dest: /etc/motd
    content: |
      Welcome to:
      {{ motd_content.stdout }}
    mode: 0644
