---
- name: 'Get the hostname'
  register: motd_hostname
  changed_when: false
  ansible.builtin.command: hostname

- name: 'Remove default MOTD'
  become: true
  ansible.builtin.file:
    path: '/etc/motd'
    state: absent

- name: 'Generate MOTD via cfonts'
  delegate_to: localhost
  register: motd_content
  changed_when: false
  ansible.builtin.command: 'cfonts {{ motd_hostname.stdout }} -f simple3d'

- name: 'Copy MOTD'
  become: true
  ansible.builtin.copy:
    dest: '/etc/motd'
    content: |
      Welcome to:
      {{ motd_content.stdout }}
    mode: 0644
