services:
  diun:
    image: ghcr.io/crazy-max/diun
    container_name: diun
    command: serve
    env_file: diun.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./diun.yaml:/diun.yml:ro
    restart: always
    labels:
      - 'diun.enable=true'
