- name: 'Install logrotate'
  become: true
  ansible.builtin.apt:
    name: logrotate
    state: latest

- name: "Copy logrotate configurations"
  become: true
  tags: [config]
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ logrotate_conf_dir }}/{{ item | basename | regex_replace('.j2','') }}"
    mode: 0644
  with_fileglob: './templates/config/*.j2'
