- name: 'Install logrotate'
  become: true
  ansible.builtin.apt:
    name: logrotate
    state: latest

- name: 'Check if user mail is present'
  become: true
  register: user_mail
  ansible.builtin.stat:
    path: '/var/mail/{{ main_user }}'

- name: 'Check if root mail is present'
  become: true
  register: root_mail
  ansible.builtin.stat:
    path: '/var/mail/root'

- name: 'Copy logrotate configurations'
  become: true
  tags: [config]
  notify: restart_logrotate
  ansible.builtin.template:
    src: '{{ item }}'
    dest: "{{ logrotate_conf_dir }}/{{ item | basename | regex_replace('.j2', '') }}"
    mode: 0644
  with_fileglob: './templates/config/*.j2'
