- name: "Install asdf"
  homebrew:
    name: asdf

# - name: "Source asdf"
#   lineinfile:
#     path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/sources.zsh"
#     line: source $(brew --prefix asdf)/asdf.sh

- name: "Reload shell"
  shell: rehash
  args:
    executable: /usr/local/bin/zsh

- name: "Add all languages"
  shell: asdf plugin add {{ item }}
  register: asdf_plugin
  failed_when:
    - asdf_plugin.stderr != ''
    - '"already added" not in asdf_plugin.stderr'
  loop:
    - nodejs
    - ruby
    - python
    - golang

- name: "Get latest nodejs version"
  shell: asdf latest nodejs
  register: node_latest
- name: "Install nodejs {{ node_latest.stdout }}"
  shell: "asdf install nodejs {{ node_latest.stdout }}"
  register: asdf_nodejs_installed
  failed_when:
    - asdf_nodejs_installed.rc != 0
    - '"already added" not in asdf_nodejs_installed.stderr'
- name: "Set global nodejs {{ node_latest.stdout }}"
  shell: "asdf global nodejs {{ node_latest.stdout }}"

- name: "Get latest ruby version"
  shell: asdf latest ruby
  register: node_latest
- name: "Install ruby {{ node_latest.stdout }}"
  shell: "asdf install ruby {{ node_latest.stdout }}"
  register: asdf_ruby_installed
  failed_when:
    - asdf_ruby_installed.rc != 0
    - '"already added" not in asdf_ruby_installed.stderr'
- name: "Set global ruby {{ node_latest.stdout }}"
  shell: "asdf global ruby {{ node_latest.stdout }}"

- name: "Get latest python version"
  shell: asdf latest python
  register: node_latest
- name: "Install python {{ node_latest.stdout }}"
  shell: "asdf install python {{ node_latest.stdout }}"
  register: asdf_python_installed
  failed_when:
    - asdf_python_installed.rc != 0
    - '"already added" not in asdf_python_installed.stderr'
- name: "Set global python {{ node_latest.stdout }}"
  shell: "asdf global python {{ node_latest.stdout }}"

- name: "Get latest golang version"
  shell: asdf latest golang
  register: node_latest
- name: "Install golang {{ node_latest.stdout }}"
  shell: "asdf install golang {{ node_latest.stdout }}"
  register: asdf_golang_installed
  failed_when:
    - asdf_golang_installed.rc != 0
    - '"already added" not in asdf_golang_installed.stderr'
- name: "Set global golang {{ node_latest.stdout }}"
  shell: "asdf global golang {{ node_latest.stdout }}"
