groups:
  - name: job_alerts
    rules:
      - alert: JobTelegrafMissing
        expr: absent(up{job="telegraf"})
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: Prometheus job missing (instance {{ $labels.instance }})
          description: "Telegraf job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - name: prometheus_alerts
    rules:
      - alert: PrometheusLargeScrape
        expr: increase(prometheus_target_scrapes_exceeded_sample_limit_total[10m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Prometheus large scrape (instance {{ $labels.instance }})
          description: "Prometheus has many scrapes that exceed the sample limit\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - name: host_hw_alerts
    rules:
      - alert: HighCPUIOWait
        expr: avg by (host) (rate(cpu_usage_iowait{cpu="cpu-total"}[5m])) * 100 > 5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High IOWAIT (host: {{ $labels.host }})"
          description: "CPU IOWAIT exceeded 10%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: DiskWillFillIn4Hours
        expr: predict_linear(node_filesystem_free_bytes{job="node_exporter", fstype="ext4", mountpoint!="/tmp"}[1h], 4 * 3600) < 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk space is runnig out {{ $labels.instance }}"
          description: "Low disk space on path:\n VALUE = {{ $labels.mountpoint }}\n LABELS = {{ $labels }}"
