version: '3'

services:
  docker_socket_proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker_socket_proxy
    env_file: docker_socket_proxy.env
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always
