- name: 'Download drivers for generic 7" HDMI LCD'
  tags: [lcd]
  ansible.builtin.git:
    repo: 'https://github.com/goodtft/LCD-show'
    dest: '{{ ansible_env.HOME }}/drivers/LCD-show'

- name: 'Ensure scripts are executable'
  ansible.builtin.file:
    mode: 0755
    path: '{{ ansible_env.HOME }}/drivers/LCD-show'
    recurse: true

- name: 'Build & install for generic 7" HDMI LCD'
  tags: [lcd]
  become: true
  changed_when: true
  ansible.builtin.command: './LCD7C-show'
  args:
    chdir: '{{ ansible_env.HOME }}/drivers/LCD-show'
