- name: 'Download drivers for generic 7" HDMI LCD'
  tags:
    - lcd
  git:
    repo: https://github.com/goodtft/LCD-show
    dest: "{{ ansible_env.HOME }}/drivers/LCD-show"

- name: 'Build & install for generic 7" HDMI LCD'
  tags:
    - lcd
  become: true
  shell: |
    chmod -R 755 {{ ansible_env.HOME }}/drivers/LCD-show
    cd {{ ansible_env.HOME }}/drivers/LCD-show
    ./LCD7C-show
