- name: 'Download drivers for MHS 3.5" GPIO LCD'
  tags: [lcd]
  ansible.builtin.git:
    dest: '{{ ansible_env.HOME }}/drivers/LCD-show'
    repo: 'https://github.com/goodtft/LCD-show'

- name: 'Set folder permissions'
  become: true
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/drivers/LCD-show'
    mode: 0755
    recurse: yes
    owner: '{{ main_user }}'
    group: '{{ main_user }}'

- name: 'Build & install for MHS 3.5" GPIO LCD'
  tags: [lcd]
  become: true
  changed_when: true
  ansible.builtin.command: './MHS35-show'
  args:
    chdir: '{{ ansible_env.HOME }}/drivers/LCD-show'

- name: 'Wait for reboot'
  tags: [lcd]
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
