- hosts: localhost
  connection: local

  tasks:
      # TODO: Only run this if rectangle is installed
    - name: "Copy Rectangle config"
      copy:
        src: ../../files/configs/macos/rectangle.plist
        dest: "{{ ansible_env.HOME }}/Library/Preferences/com.knollsoft.Rectangle.plist"
        mode: 0600

    - name: "Copy iTerm profile"
      copy:
        src: ../../files/configs/macos/iterm2_profile.json
        dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/ansible_imported_profile.json"

    - name: "Install iTerm ZSH support"
      get_url:
        url: https://iterm2.com/shell_integration/zsh
        dest: "{{ ansible_env.HOME }}/.iterm2_shell_integration.zsh"
