- hosts: localhost
  connection: local

  vars_files:
    - ./brew/vars_apps.yaml
    - ./brew/vars_packages.yaml
    - ./vars/mas_apps.yaml
  vars:
    homebrew_upgrade_all_packages: no
    homebrew_taps:
      - homebrew/cask-drivers
      - homebrew/cask-fonts
      - homebrew/cask-versions
      - homebrew/command-not-found
      - homebrew/core
      - homebrew/services

  roles:
    - role: geerlingguy.mac.dock
    - role: geerlingguy.mac.homebrew
      tags:
        - brew
    - role: geerlingguy.mac.mas
      tags:
        - mas
    - role: ../../roles/zsh
      tags: zsh

  tasks:
    - name: "Use brew bash"
      tags: bash
      become: true
      lineinfile:
        path: /etc/shells
        state: present
        line: "/usr/local/bin/bash"

    - name: "Install Xcode devtools"
      tags: dev
      become: true
      command: xcode-select --install
      register: xcode_devtools_installed
      changed_when: '"command line tools are already installed" not in xcode_devtools_installed.stderr'
      failed_when:
        - xcode_devtools_installed.rc != 0
        - '"command line tools are already installed" not in xcode_devtools_installed.stderr'

    - name: "Copy dotfiles (common)"
      tags: dotfiles
      synchronize:
        src: ../../files/dotfiles/
        dest: "{{ ansible_env.HOME }}/"

    - name: "Powerline Fonts"
      include_tasks: ../../tasks/powerline-fonts.yaml

    - name: "Set Git configuration"
      tags:
        - git
        - dev
      command: git config --global credential.helper osxkeychain
