ansible_user: root

# Directories
docker_compose_dir: '{{ ansible_env.HOME }}/docker-compose'
tmp_dir: /tmp
systemd_dir: '/etc/systemd/system'

# Flags
is_rpi_host: false

# Other
guid: '1000'

main_user: 'thibmaek'

user_timezone: 'Europe/Brussels'

# Packages to install on all systems regardless of CPU architecture, package manager or OS.
install_packages:
  - autojump
  - bash
  - bash-completion
  - bat
  - binwalk
  - btop
  - coreutils
  - curl
  - exa
  - findutils
  - fzf
  - gcc
  - git
  - gnupg
  - grep
  - htop
  - httpie
  - iperf3
  - jq
  - less
  - lsof
  - magic-wormhole
  - make
  - moreutils
  - nano
  - ncdu
  - neofetch
  - neovim
  - netcat
  - nmap
  - openssl
  - rsync
  - screen
  - shellcheck
  - tmux
  - tree
  - unzip
  - vim
  - wget
