version: "3"

services:
  loki:
    image: grafana/grafana
    container_name: grafana
    env_file: grafana.env
    ports:
      - 3000:3000
    volumes:
      - ./data:/var/lib/grafana
      - ./config/config.ini:/usr/share/grafana/conf/defaults.ini
    restart: always
