- name: 'Install python 3 packages'
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-venv
    state: latest
    update_cache: true

- name: 'Ensure the github python module is installed'
  become: true
  ansible.builtin.pip:
    name: github3.py
