---
docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'software-properties-common'
  - 'python3-pip'
  - 'virtualenv'
  - 'python3-setuptools'

docker_pkgs:
  - 'docker-ce'
  - 'docker-ce-cli'
