version: "3"

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    env_file: grafana.env
    volumes:
      - ./plugins:/var/lib/grafana/plugins
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always

volumes:
  grafana_data:
