version: "3"

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    env_file: grafana.env
    volumes:
      - ./data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always
