- name: 'Ensure .ssh dir exists'
  ansible.builtin.file:
    path: "/home/{{ main_user }}/.ssh"
    state: directory
    owner: '{{ main_user }}'
    group: '{{ main_user }}'
    mode: 0700

- name: 'Add SSH keys'
  tags: [ssh_keys]
  ansible.posix.authorized_key:
    user: '{{ main_user }}'
    key: "{{ lookup('file', item) }}"
  with_fileglob: '../files/keys/ssh/*'

- name: 'Set new sshd port to use'
  ansible.builtin.set_fact:
    sshd_port: '{{ ssh_configure_port }}'

- name: 'Copy sshd config'
  become: true
  tags: [ssh_config]
  ansible.builtin.template:
    src: '../templates/sshd_config.j2'
    dest: '/etc/ssh/sshd_config'
    mode: 0644

- name: 'Output SSH port'
  tags: [ssh_config]
  notify: ['restart_sshd']
  changed_when: true
  ansible.builtin.debug:
    msg: 'SSH now using port {{ sshd_port }}'
