- name: 'Include tasks (Debian)'
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: './debian.yaml'

- name: 'Include tasks (macOS)'
  when: ansible_os_family == 'Darwin'
  ansible.builtin.include_tasks: './macos.yaml'
