- name: 'Add golang plugin'
  register: asdf_add_golang
  failed_when:
    - asdf_add_golang.rc != 0
    - '"already added" not in asdf_add_golang.stderr'
  command: 'asdf plugin add golang'

- name: 'Install prereqs'
  when: ansible_os_family == 'Debian'
  apt:
    state: latets
    name: coreutils

- name: 'Install latest go'
  register: asdf_golang_installed
  changed_when: '"already added" not in asdf_golang_installed.stdout'
  failed_when:
    - asdf_golang_installed.rc != 0
    - '"already added" not in asdf_golang_installed.stderr'
  command: 'asdf install golang latest'

- name: 'Set global go version' # noqa no-changed-when
  command: 'asdf global golang latest'

- name: 'Install additional golang version'
  when: golang_versions is defined and (golang_versions | length > 0)
  command: 'asdf install golang {{ item }}'
  loop: golang_versions
