- name: 'Source asdf.sh'
  when: ansible_via_git
  lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    line: '. "{{ asdf_git_dir }}/asdf.sh"'

- name: 'Source bash completions'
  when: ansible_via_git
  lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    line: '. "{{ asdf_git_dir }}/completions/asdf.bash"'

- name: 'Source asdf.sh'
  when: ansible_via_homebrew
  blockinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    block: |
      # asdf
      . $(brew --prefix asdf)/libexec/asdf.sh
      . $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash

- name: 'Reload the shell'
  shell: 'exec $SHELL -l'
