- name: 'Install prereqs'
  tags: [apt]
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - git
    state: latest

- name: 'Clone asdf repo'
  tags: [apt]
  ansible.builtin.git:
    repo: '{{ asdf_git_repo }}'
    dest: '{{ asdf_git_dir }}'

- name: "Set fact 'asdf_via_git'"
  ansible.builtin.set_fact:
    asdf_via_git: true
