# Installs asdf on the system
---
- name: 'Install asdf (git)'
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: './install_debian.yaml'

- name: 'Install asdf (brew)'
  when: ansible_os_family == 'Darwin'
  ansible.builtin.include_tasks: './install_macos.yaml'

- name: 'Source asdf in shell (bash)'
  when: '"bash" in ansible_user_shell'
  ansible.builtin.include_tasks: './install_bash.yaml'

- name: 'Source asdf in shell (zsh)'
  when: '"zsh" in ansible_user_shell'
  ansible.builtin.include_tasks: './install_zsh.yaml'

- name: 'Update existing plugins'
  tags: [update]
  changed_when: true
  ansible.builtin.command: 'asdf plugin update --all'

- name: 'Install runtimes'
  tags: [runtimes]
  ansible.builtin.include_tasks: './runtimes/{{ item }}.yaml'
  loop:
    - golang
    - nodejs
    - python
    - ruby
