- name: "Install Node.js PGP keys"
  shell: |
    bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'

- name: "Get latest nodejs version"
  shell: asdf latest nodejs
  register: node_latest

- name: "Install node@{{ node_latest.stdout }}"
  register: asdf_nodejs_installed
  changed_when: '"already added" not in asdf_nodejs_installed.stdout'
  failed_when:
    - asdf_nodejs_installed.rc != 0
    - '"already added" not in asdf_nodejs_installed.stderr'
  shell: "asdf install nodejs {{ node_latest.stdout }}"

- name: "Set global to node@{{ node_latest.stdout }}"
  shell: "asdf global nodejs {{ node_latest.stdout }}"

- name: "Install additional nodejs version"
  when: nodejs_versions is defined and (nodejs_versions | length > 0)
  shell: "asdf install nodejs {{ item }}"
  loop: nodejs_versions
