---
- name: 'Add nodejs plugin'
  register: asdf_add_node
  failed_when:
    - asdf_add_node.rc != 0
    - '"already added" not in asdf_add_node.stderr'
  command: 'asdf plugin add nodejs'

- name: 'Install latest node LTS'
  register: asdf_install_node
  changed_when: '"already added" not in asdf_install_node.stdout'
  failed_when:
    - asdf_install_node.rc != 0
    - '"is already installed" not in asdf_install_node.stderr'
  command: 'asdf install nodejs {{ asdf_lts_versions.nodejs }}'

- name: 'Set global to node LTS' # noqa no-changed-when
  command: 'asdf global nodejs {{ asdf_lts_versions.nodejs }}'

- name: 'Install additional nodejs version'
  when: nodejs_versions is defined and (nodejs_versions | length > 0)
  command: 'asdf install nodejs {{ item }}'
  loop: nodejs_versions
