- name: 'Install prereqs'
  when: ansible_os_family == 'Darwin'
  homebrew:
    name:
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib

- name: 'Install prereqs'
  when: ansible_os_family == 'Debian'
  apt:
    name:
      - build-essential
      - curl
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - make
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev

- name: 'Install latest python 3'
  register: asdf_python_install
  changed_when: '"already added" not in asdf_python_install.stdout'
  failed_when:
    - asdf_python_install.rc != 0
    - '"already added" not in asdf_python_install.stderr'
  command: 'asdf install python latest:{{ asdf_lts_versions.python }}'

- name: 'Set global to python@{{ python_latest.stdout }}' # noqa no-changed-when
  command: "asdf global python latest:{{ asdf_lts_versions.python }}"

- name: 'Install additional python version'
  when: python_versions is defined and (python_versions | length > 0)
  command: 'asdf install python {{ item }}'
  loop: python_versions
