- name: 'Install latest ruby 2'
  register: asdf_ruby_install
  changed_when: '"already added" not in asdf_ruby_install.stdout'
  failed_when:
    - asdf_ruby_install.rc != 0
    - '"already added" not in asdf_ruby_install.stderr'
  command: 'asdf install ruby latest:{{ asdf_lts_versions.ruby }}'

- name: 'Set global to ruby@{{ ruby_latest.stdout }}' # noqa no-changed-when
  command: 'asdf global ruby latest:{{ asdf_lts_versions.ruby }}'

- name: 'Install additional ruby version'
  when: ruby_versions is defined and (ruby_versions | length > 0)
  command: 'asdf install ruby {{ item }}'
  loop: ruby_versions
