- name: "Get latest ruby version"
  shell: asdf latest ruby
  register: ruby_latest

- name: "Install ruby@{{ ruby_latest.stdout }}"
  register: asdf_ruby_installed
  changed_when: '"already added" not in asdf_ruby_installed.stdout'
  failed_when:
    - asdf_ruby_installed.rc != 0
    - '"already added" not in asdf_ruby_installed.stderr'
  shell: "asdf install ruby {{ ruby_latest.stdout }}"

- name: "Set global to ruby@{{ ruby_latest.stdout }}"
  shell: "asdf global ruby {{ ruby_latest.stdout }}"

- name: "Install additional ruby version"
  when: ruby_versions is defined and (ruby_versions | length > 0)
  shell: "asdf install ruby {{ item }}"
  loop: ruby_versions
