- name: 'Install motioneye dependencies'
  become: true
  apt:
    name: '{{ motioneye_dependencies }}'

- name: 'Install motion dependencies'
  become: true
  apt:
    name: '{{ motion_dependencies }}'

- name: 'Install motioneye'
  become: true
  pip:
    name: 'motioneye'
    state: latest

- name: 'Create motioneye config dir'
  become: true
  file:
    group: '{{ main_user }}'
    mode: 0755
    owner: '{{ main_user }}'
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ motioneye_config_dir }}'
    - '{{ motioneye_media_dir }}'

- name: 'Copy motioneye config'
  become: true
  template:
    mode: 0644
    src: 'motioneye.conf.j2'
    dest: '{{ motioneye_config_dir }}/motioneye.conf'

- name: 'Copy systemd service'
  become: true
  template:
    mode: 0600
    src: 'motioneye.service.j2'
    dest: '/etc/systemd/system/motioneye.service'

- name: 'Enable & restart motioneye service'
  become: true
  systemd:
    daemon_reload: true
    enabled: true
    name: motioneye
    state: restarted
