- name: 'Install motioneye dependencies'
  tags: [apt]
  become: true
  ansible.builtin.apt:
    name: '{{ motioneye_dependencies }}'
    state: latest

- name: 'Install motion dependencies'
  tags: [apt]
  become: true
  ansible.builtin.apt:
    name: '{{ motion_dependencies }}'
    state: latest

- name: 'Install motioneye'
  tags: [pip]
  become: true
  ansible.builtin.pip:
    name: motioneye
    state: latest

- name: 'Create motioneye config dir'
  become: true
  ansible.builtin.file:
    group: '{{ main_user }}'
    mode: 0755
    owner: '{{ main_user }}'
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ motioneye_config_dir }}'
    - '{{ motioneye_media_dir }}'

- name: 'Copy motioneye config'
  become: true
  ansible.builtin.template:
    src: 'templates/motioneye.conf.j2'
    dest: '{{ motioneye_config_dir }}/motioneye.conf'
    mode: 0644

- name: 'Copy systemd service'
  become: true
  notify: restart_motioneye
  ansible.builtin.template:
    mode: 0600
    src: 'motioneye.service.j2'
    dest: '{{ motioneye_systemd_unit }}'
