- name: 'Install ZSH + Oh My ZSH'
  ansible.builtin.include_role:
    name: vaulttec.zsh
  vars:
    zsh_user: '{{ main_user }}'
    zsh_ohmy_theme: spaceship
    zsh_ohmy_disable_auto_update: false
    zsh_ohmy_plugins:
      - asdf
      - docker
      - docker-compose
      - git
      - git-flow
      - httpie
      - fzf-tab
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    zsh_ohmy_custom_plugins:
      - name: fzf-tab
        repo: 'https://github.com/Aloxaf/fzf-tab'
      - name: zsh-autosuggestions
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      - name: zsh-syntax-highlighting
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    zsh_ohmy_custom_themes:
      - name: spaceship-prompt
        repo: 'https://github.com/denysdovhan/spaceship-prompt'

- name: 'Create .zshrc.local'
  ansible.builtin.template:
    mode: 0755
    src: templates/zshrc.local.j2
    dest: "{{ ansible_env.HOME }}/.zshrc.local"

- name: 'Link Spaceship Prompt'
  ansible.builtin.file:
    src: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme'
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme'
    state: link

- name: 'Copy dotfiles to oh-my-zsh'
  ansible.builtin.template:
    mode: 0755
    src: '{{ item }}'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item | basename | regex_replace('.j2', '') }}"
  with_fileglob: '../templates/dotfiles/*.j2'

- name: 'Add custom shell completions to oh-my-zsh'
  ansible.builtin.copy:
    src: ./files/completions
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/completions"
