- name: 'Install ZSH + Oh My ZSH'
  include_role:
    name: vaulttec.zsh
  vars:
    zsh_user: '{{ main_user }}'
    zsh_ohmy_theme: spaceship
    zsh_ohmy_disable_auto_update: false
    zsh_ohmy_plugins:
      - git
      - git-flow
      - zsh-autosuggestions
    zsh_ohmy_custom_plugins:
      - name: zsh-autosuggestions
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    zsh_ohmy_custom_themes:
      - name: spaceship-prompt
        repo: 'https://github.com/denysdovhan/spaceship-prompt'

- name: 'Install Starship'
  include_tasks: './starship.yaml'

- name: 'Create .zshrc.local'
  template:
    mode: 0755
    src: templates/zshrc.local.j2
    dest: "{{ ansible_env.HOME }}/.zshrc.local"

- name: 'Link Spaceship Prompt'
  file:
    src: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship/spaceship.zsh-theme'
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme'
    state: link

- name: 'Copy dotfiles to oh-my-zsh'
  template:
    mode: 0755
    src: '{{ item }}'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item | basename | regex_replace('.j2','.zsh') }}"
  with_fileglob: ../templates/dotfiles/*.j2
