---
- name: 'Download raspotify install script'
  become: true
  ansible.builtin.get_url:
    url: '{{ raspotify_script_url }}'
    dest: '{{ tmp_dir }}/raspotify.sh'
    mode: 0755

- name: 'Install raspotify'
  become: true
  ansible.builtin.command: './raspotify.sh'
  changed_when: false
  args:
    chdir: '{{ tmp_dir }}'

- name: 'Remove raspotify install script'
  become: true
  ansible.builtin.file:
    path: '{{ tmp_dir }}/raspotify.sh'
    state: absent

- name: 'Set sound device'
  become: true
  ansible.builtin.replace:
    dest: '{{ raspotify_config_file }}'
    regexp: '^#LIBRESPOT_DEVICE="default"'
    replace: 'LIBRESPOT_DEVICE="{{ raspotify_sound_device }}"'

- name: 'Set device type'
  become: true
  ansible.builtin.replace:
    dest: '{{ raspotify_config_file }}'
    regexp: '^#LIBRESPOT_DEVICE_TYPE="speaker"'
    replace: 'LIBRESPOT_DEVICE_TYPE="{{ raspotify_device_type }}"'
