---
- name: 'Install glances'
  become: true
  ansible.builtin.pip:
    name:
      - glances
      - bottle
    state: latest

- name: 'Copy systemd service'
  become: true
  notify: restart_glances
  ansible.builtin.copy:
    src: ./files/glances.service
    dest: /etc/systemd/system/glances.service
    mode: 0644
