services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    env_file: gitea.env
    ports:
      - 3000:3000
      - 222:22
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
