- name: 'Install Octodash dependencies'
  tags: [apt]
  become: true
  ansible.builtin.apt:
    name: '{{ octodash_deps }}'

- name: 'Install optimized driver (xf86-video-fbturbo)'
  tags: [turbo_driver]
  ansible.builtin.include_tasks: 'turbo-driver.yaml'

- name: 'Reboot'
  tags: [reboot]
  ansible.builtin.reboot:

- name: 'Download OctoDash'
  ansible.builtin.get_url:
    dest: '{{ ansible_env.HOME }}/octodash_install.sh'
    url: '{{ octodash_repo }}/raw/main/scripts/install.sh'
    mode: 0775

- name: 'Display success prompt'
  ansible.builtin.pause:
    seconds: 1
    prompt: |
      ==============================================================================
        Bootstrapping done!

        The OctoDash setup itself is interactive.
        Run it from '{{ ansible_env.HOME }}/octodash_install.sh' on the host to continue setup
      ==============================================================================
