version: '3'

services:
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    env_file: dozzle.env
    ports:
      - 9999:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
