services:
  uptime_kuma:
    image: louislam/uptime-kuma
    container_name: uptime_kuma
    env_file: uptime_kuma.env
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
