version: '3'

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    env_file: diun.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./diun.yaml:/diun.yml:ro
    restart: always
