version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    env_file: plex.env
    network_mode: host
    volumes:
      - ./data:/config
      - /tv:/data/tv
      - /movies:/data/movies
      - /music:/data/music
      - /videos:/data/videos
      - /mnt/transcode:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  plex_meta_manager:
    image: lscr.io/linuxserver/plex-meta-manager
    depends_on: [plex]
    container_name: plex-meta-manager
    env_file: plex-meta-manager.env
    volumes:
      - ./plex_meta_manager:/config
    restart: unless-stopped

  plex_exporter:
    image: granra/plex_exporter
    container_name: plex_exporter
    depends_on: [plex]
    ports:
      - 9594:9594
    volumes:
      - ./plex_exporter/config.yaml:/etc/plex_exporter/config.yaml
    restart: unless-stopped
