services:
  maintainerr:
    image: ghcr.io/jorenn92/maintainerr
    container_name: maintainerr
    env_file: maintainerr.env
    ports:
      - 6246:6246
    volumes:
      - ./data:/opt/data
    restart: unless-stopped
