#!/usr/bin/env bash

# ------------------------------------------------------------------------------
# Silence function output by redirecting output to /dev/null
#
# Usage:
#   silent echo "ok"
# ------------------------------------------------------------------------------
function silent() {
  "$@" >& /dev/null
}

function flatten_dir() {
  find "$1" -mindepth 2 -type f -exec mv -i '{}' "$1" ';'
}

function fs() {
  if du -b /dev/null > /dev/null 2>&1; then
    local arg=-sbh;
  else
    local arg=-sh;
  fi
  if [[ -n "$@" ]]; then
    du $arg -- "$@" | gsort -h;
  else
    du $arg .[^.]* * | gsort -h;
  fi;
}

function mkd() {
  mkdir -p "$@" && cd "$@" || return;
}
