services:
  gotify:
    image: gotify/server
    container_name: gotify
    env_file: gotify.env
    ports:
      - 8081:80
    volumes:
      - ./config.yaml:/etc/gotify/config.yml
      - ./data:/app/data
    restart: always
