- name: 'Volumion: i2c LCD'

  hosts: volumio

  become: true

  tasks:
    - name: 'Install required LCD packages and bindings'
      ansible.builtin.apt:
        update_cache: true
        name:
          - i2c-tools
          - lcdproc
          - python3
          - python3-pip
          - python-smbus
          - python-mpd

    - name: 'Install mpdlcd python package'
      ansible.builtin.pip:
        executable: pip3
        name: mpdlcd

    - name: 'Download mpdlcd.conf'
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/rbarrois/mpdlcd/master/mpdlcd.conf
        dest: /etc/mpdlcd.conf
        mode: 0644

    - name: 'Create drivers folder'
      ansible.builtin.file:
        mode: 0755
        path: '/home/volumio/drivers'
        state: directory
        owner: volumio
        group: volumio

    - name: 'Download LCD drivers'
      ansible.builtin.get_url:
        url: https://github.com/wilberforce/lcdproc/raw/master/hd44780.so
        dest: "/home/volumio/drivers/hd44780.so"
        owner: volumio
        group: volumio
        mode: 0644

    - name: 'Ensure LCDd.conf is recreated'
      ansible.builtin.file:
        path: /etc/LCDd.conf
        state: absent

    - name: 'Create LCDd.conf'
      ansible.builtin.copy:
        src: ./files/LCDd.conf
        dest: /etc/LCDd.conf
        mode: 0644

    - name: 'Create init file for mpdlcd'
      ansible.builtin.copy:
        src: ./files/mpdlcd.service
        dest: /etc/systemd/system/mpdlcd.service
        mode: 0644

    - name: 'Reload init files' # noqa command-instead-of-shell
      changed_when: true
      ansible.builtin.shell: |
        update-rc.d LCDd defaults
        systemctl enable mpdlcd
        systemctl start mpdlcd

    - name: 'Reboot'
      ansible.builtin.reboot:
        msg: 'Reboot initiated by Ansible'
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
