- hosts: volumio
  tasks:
    - name: "Update Volumio to the latest version"
      tags: update
      shell: volumio updater forceupdate --yes
    - name: "Sync radio favorites"
      copy:
        dest: /data/favourites/radio-favourites
        src: ./files/radio-favourites
    - name: "Update music database"
      shell: mpc update NAS
