- hosts: localhost
  connection: local

  vars_files:
    - ./brew/vars_apps.yaml
    - ./brew/vars_packages.yaml
    - ./mas_apps.yaml

  roles:
    - role: geerlingguy.homebrew
      vars:
        homebrew_upgrade_all_packages: no
        homebrew_taps:
          - homebrew/cask-drivers
          - homebrew/cask-fonts
          - homebrew/cask-versions
          - homebrew/command-not-found
          - homebrew/core
          - homebrew/services

  tasks:
    - name: "Use brew bash"
      become: true
      lineinfile:
        path: /etc/shells
        state: present
        line: "/usr/local/bin/bash"
    - name: "Install Xcode devtools"
      become: true
      command: xcode-select --install
    - name: "Install App Store apps (via mas)"
      shell: "mas install {{ item }}"
      loop: "{{ mas_apps }}"
    - name: "Copy dotfiles (common)"
      copy:
        dest: "{{ ansible_env.HOME }}"
        src: ../../files/dotfiles/common
    - name: "Copy dotfiles (oh-my-zsh)"
      copy:
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom"
        src: ../../files/dotfiles/macos
