- hosts: localhost
  connection: local

  vars_files:
    - ./brew/vars_apps.yaml
    - ./brew/vars_packages.yaml

  roles:
    - role: geerlingguy.homebrew
      vars:
        homebrew_upgrade_all_packages: no
        homebrew_taps:
          - homebrew/cask-drivers
          - homebrew/cask-fonts
          - homebrew/cask-versions
          - homebrew/command-not-found
          - homebrew/core
          - homebrew/services

  tasks:
    - name: "Use brew bash"
      become: true
      lineinfile:
        path: /etc/shells
        state: present
        line: "/usr/local/bin/bash"
    - name: "Install Xcode devtools"
      become: true
      command: xcode-select --install
