# Tasks for docker-compose
---
- name: 'Ensure that Docker CLI plugin dir exists'
  tags: [compose]
  block:
    - name: 'Check if Docker CLI plugin dir dir exists'
      register: cli_plugin_dir
      ansible.builtin.stat:
        path: '{{ docker_cli_plugin_dir }}'

    - name: 'Create the Docker CLI plugin dir'
      when: not cli_plugin_dir.stat.exists
      ansible.builtin.file:
        group: '{{ main_user }}'
        owner: '{{ main_user }}'
        path: '{{ docker_cli_plugin_dir }}'
        state: directory
        recurse: true

- name: 'Install docker-compose'
  tags: [compose]
  become: true
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: latest

- name: 'Ensure the docker-compose folder exists'
  tags: [compose]
  block:
    - name: 'Check if folder exists'
      register: compose_folder
      ansible.builtin.stat:
        path: "{{ docker_compose_dir }}"

    - name: 'Create the docker-compose folder'
      when: not compose_folder.stat.exists
      ansible.builtin.file:
        path: '{{ docker_compose_dir }}'
        group: '{{ main_user }}'
        owner: '{{ main_user }}'
        recurse: true
        state: directory

- name: 'Copy docker scripts'
  tags: [compose]
  ansible.builtin.copy:
    dest: '{{ docker_compose_dir }}/'
    src: '{{ item }}'
    mode: 0755
  with_fileglob: '../files/*.sh'
