# Tasks for docker-compose
---
- name: 'Ensure that Docker CLI plugin dir exists'
  tags: [compose]
  block:
    - name: 'Check if Docker CLI plugin dir dir exists'
      register: cli_plugin_dir
      ansible.builtin.stat:
        path: '{{ docker_cli_plugin_dir }}'

    - name: 'Create the Docker CLI plugin dir'
      when: not cli_plugin_dir.stat.exists
      ansible.builtin.file:
        group: '{{ main_user }}'
        owner: '{{ main_user }}'
        path: '{{ docker_cli_plugin_dir }}'
        state: directory
        recurse: true

- name: 'Ensure github3.py is installed to get docker/compose release'
  become: true
  ansible.builtin.pip:
    name: github3.py

- name: 'Grab latest docker/compose binary'
  tags: [compose]
  block:
    - name: 'Get latest release from docker/compose Github'
      register: docker_compose_latest_release
      github_release:
        action: latest_release
        user: docker
        repo: compose

    - name: 'Grab docker-compose binary (x86_64)'
      when: ansible_architecture == 'x86_64'
      ansible.builtin.get_url:
        dest: '{{ docker_cli_plugin_dir }}/docker-compose'
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_latest_release['tag'] }}/docker-compose-linux-x86_64"
        mode: 0755

    - name: 'Grab docker-compose binary (arm)'
      when: ansible_architecture == 'arm'
      ansible.builtin.get_url:
        dest: '{{ docker_cli_plugin_dir }}/docker-compose'
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_latest_release['tag'] }}/docker-compose-linux-armv7"
        mode: 0755

- name: 'Ensure the docker-compose folder exists'
  tags: [compose]
  block:
    - name: 'Check if folder exists'
      register: compose_folder
      ansible.builtin.stat:
        path: "{{ docker_compose_dir }}"

    - name: 'Create the docker-compose folder'
      when: not compose_folder.stat.exists
      ansible.builtin.file:
        path: '{{ docker_compose_dir }}'
        group: '{{ main_user }}'
        owner: '{{ main_user }}'
        recurse: true
        state: directory

- name: 'Copy docker scripts'
  tags: [compose]
  ansible.builtin.copy:
    dest: '{{ docker_compose_dir }}/'
    src: '{{ item }}'
    mode: 0755
  with_fileglob: '../files/*.sh'
