- name: 'Add buster-backports GPG key (for libseccomp2)'
  become: true
  tags: [apt]
  ansible.builtin.apt_key:
    id: '{{ item }}'
    keyserver: 'keyserver.ubuntu.com'
  loop:
    - '04EE7237B7D453EC'
    - '648ACFD622F3D138'

- name: 'Add backports repository'
  become: true
  tags: [apt]
  ansible.builtin.apt_repository:
    repo: 'deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free'

- name: 'Update to the latest version of libseccomp2'
  become: true
  tags: [apt]
  ansible.builtin.apt:
    default_release: '{{ ansible_distribution_release }}-backports'
    name: libseccomp2
    state: latest
    update_cache: yes

- name: 'Switch to pip3'
  community.general.alternatives:
    name: pip
    link: '/usr/bin/pip'
    path: '/usr/bin/pip3'

- name: 'Switch to python3'
  community.general.alternatives:
    name: python
    link: '/usr/bin/python'
    path: '/usr/bin/python3'
