services:
  endlessh:
    image: lscr.io/linuxserver/endlessh
    container_name: endlessh
    env_file: endlessh.env
    ports:
      - 22:2222
    volumes:
      - ./config:/config
    restart: unless-stopped
