- when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: './debian.yaml'

- when: ansible_os_family == 'Darwin'
  ansible.builtin.include_tasks: './macos.yaml'

- name: 'Add Starship to Bash'
  when: '"bash" in ansible_user_shell'
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.bash_profile'
    line: 'eval "$(starship init bash)"'

- name: 'Add Starship to ZSH'
  when: '"zsh" in ansible_user_shell'
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.zshrc.local'
    line: 'eval "$(starship init zsh)"'
