version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    env_file: influxdb.env
    ports:
      - 8086:8086
    volumes:
      - ./data:/var/lib/influxdb2
    restart: always
