- name: 'Install duf from .deb package'
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: './debian.yaml'

- name: 'Install duf'
  when: ansible_os_family == 'Darwin'
  community.general.homebrew:
    name: duf
    state: latest
