services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    env_file: n8n.env
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
