- hosts: all
  tasks:
    - name: Update apt packages
      become: true
      tags: apt
      apt:
        upgrade: dist
        update_cache: true

    - name: Install apt packages
      become: true
      tags: apt
      apt:
        state: latest
        name:
          - build-essential
          - curl
          - gdisk
          - git
          - htop
          - jq
          - lsof
          - magic-wormhole
          - moreutils
          - ncdu
          - python3
          - python3-dev
          - python3-pip
          - python3-setuptools
          - python3-venv
          - screen
          - tree
          - vim
          - xclip

    - include: ../tasks/dev/bat.yaml
    - include: ../tasks/dev/nano.yaml

    - name: "Install dotfiles repository"
      git:
        repo: https://github.com/thibmaek/linux-confs
        dest: "{{ ansible_env.HOME }}/.linux-confs"
