- hosts: all
  tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: yes
        state: latest
        name:
          - build-essential
          - curl
          - gdisk
          - git
          - htop
          - jq
          - lsof
          - magic-wormhole
          - moreutils
          - ncdu
          - python3
          - python3-dev
          - python3-pip
          - python3-setuptools
          - python3-venv
          - screen
          - tree
          - vim
          - xclip

    - include: ./tasks/bat.yaml

    - name: Install syntax highlighting for nano
      get_url:
        url: https://raw.githubusercontent.com/scopatz/nanorc/master/install.sh
        dest: /tmp/nano_syntax_highlight_install.sh
        mode: 0755
    - shell: /tmp/nano_syntax_highlight_install.sh

    - name: Install dotfiles repository
      git:
        repo: https://github.com/thibmaek/linux-confs
        dest: "{{ ansible_env.HOME }}/.linux-confs"

    - name: Install ZSH + Oh My ZSH + Spaceship
      include_tasks: ../tasks/zsh.yaml
