# Common playbook to recurringly run on existing hosts
---
- hosts: all
  tasks:
    - name: 'Update apt packages'
      become: true
      tags: [apt]
      apt:
        upgrade: dist
        update_cache: true

    - name: 'Install packages'
      tags: [apt]
      block:
        - name: 'Install general packages'
          become: true
          apt:
            state: latest
            name: '{{ item }}'
          with_items: '{{ install_packages }}'
        - name: 'Install Debian packages'
          become: true
          apt:
            state: latest
            name:
              - build-essential
              - cockpit
              - gdisk
              - python3
              - python3-dev
              - python3-pip
              - python3-setuptools
              - python3-venv
              - smartmontools
              - util-linux
              - xclip

    - include_tasks: 'tasks/dev/nano.yaml'

    - name: 'Install dotfiles repository'
      git:
        repo: 'https://github.com/thibmaek/linux-confs'
        dest: '{{ ansible_env.HOME }}/.linux-confs'

    - name: 'Copy scripts folder'
      copy:
        src: 'files/scripts'
        dest: '{{ ansible_env.HOME }}/scripts'
        mode: 0755
