- hosts: all
  tasks:
    - name: Install apt packages
      become: true
      apt:
        pkg:
          - git
          - build-essential
          - python3
          - python3-pip
          - python3-dev
          - curl
          - moreutils
          - screen
          - tree
          - vim

    - name: Install dotfiles repository
      git:
        repo: https://github.com/thibmaek/linux-confs
        dest: "/home/{{ main_user }}/.linux-confs"
