# Common playbook to recurringly run on existing hosts
---
- hosts:
    - proxmox
    - vms
    - rpi

  roles:
    - 'roles/nano'

  tasks:
    - name: 'Update apt packages'
      become: true
      tags: [apt]
      apt:
        upgrade: true
        update_cache: true

    - name: 'Install packages'
      tags: [apt]
      block:
        - name: 'Install important system packages'
          become: true
          apt:
            name:
              - apt-transport-https
              - build-essential
              - ca-certificates
              - curl
              - software-properties-common
        - name: 'Install general packages'
          become: true
          apt:
            state: latest
            name: '{{ item }}'
          with_items: '{{ install_packages }}'
        - name: 'Install Debian packages'
          become: true
          apt:
            state: latest
            name:
              - cockpit
              - gdisk
              - openssh-client
              - python3
              - python3-dev
              - python3-pip
              - python3-setuptools
              - python3-venv
              - readline-common
              - smartmontools
              - unzip
              - util-linux
              - xclip

    - name: 'Copy scripts folder'
      copy:
        src: '../files/scripts'
        dest: '{{ ansible_env.HOME }}/scripts'
        mode: 0755

    - name: 'Set timezone'
      become: true
      timezone:
        name: Europe/Brussels
