- hosts: all
  tasks:
    - name: Install apt packages
      become: true
      apt:
        pkg:
          - build-essential
          - curl
          - git
          - htop
          - lsof
          - magic-wormhole
          - moreutils
          - python3
          - python3-dev
          - python3-pip
          - screen
          - tree
          - vim
        update_cache: yes
        state: latest

    - name: Install dotfiles repository
      git:
        repo: https://github.com/thibmaek/linux-confs
        dest: "/home/{{ main_user }}/.linux-confs"
