# Common playbook to recurringly run on existing hosts
---
- hosts: all

  roles:
    - name: 'roles/nano'
      tags: [nano]
    - name: 'roles/htop'
      tags: [htop]
    - name: 'roles/nvim'
      tags: [nvim]

  tasks:
    - name: 'Update apt packages'
      become: true
      tags: [apt]
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: 'Install packages'
      tags: [apt]
      block:
        - name: 'Install important system packages'
          become: true
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - build-essential
              - ca-certificates
              - curl
              - software-properties-common
        - name: 'Install general packages'
          become: true
          ansible.builtin.apt:
            state: latest
            name: '{{ item }}'
          with_items: '{{ install_packages }}'
        - name: 'Install Debian packages'
          become: true
          ansible.builtin.apt:
            state: latest
            name:
              - avahi-daemon
              - cockpit
              - gdisk
              - iotop
              - openssh-client
              - python3
              - python3-dev
              - python3-pip
              - python3-setuptools
              - python3-venv
              - readline-common
              - smartmontools
              - unzip
              - util-linux
              - xclip

    - name: 'Copy scripts folder'
      tags: [scripts]
      ansible.builtin.copy:
        src: '../files/scripts'
        dest: '{{ ansible_env.HOME }}/'
        mode: 0755

    - name: 'Set timezone'
      tags: [timezone]
      become: true
      community.general.timezone:
        name: '{{ user_timezone }}'
