# Set up a DNS server with optional adblocking via AdGuard Home
---
- hosts: all

  vars:
    adguard_home_version: '0.91'
    adguard_home_base_path: /opt/adguard_home
    adguard_home_user: root

  tasks:
    - name: "Execute AdGuard Home role"
      become: true
      tags:
        - adguard
      import_role:
        name: woodendoors.ansible_adguard_home
