- hosts: all
  become: true
  tasks:
    - name: Check if docker is installed already
      package:
        name:
          - docker-ce
        state: absent
      register: has_docker_installed

    - name: Install docker from official script
      shell: >
        curl -sSL https://get.docker.com | sh
      when: has_docker_installed is failed

    - name: Add user to the docker group
      when: has_docker_installed is failed
      shell: >
        usermod -aG docker {{ ansible_user }}
        usermod -aG docker {{ main_user }}

    - name: Upgrade Docker
      when: has_docker_installed is succeeded
      apt:
        name: docker-ce docker-ce-cli
        state: latest
        update_cache: yes

    - name: Report the Docker version
      shell: docker --version

    - name: Install docker-compose
      pip:
        executable: pip3
        name: docker-compose
        extra_args: --upgrade
      register: has_docker_compose_installed

    - name: Create config dir for docker-compose files
      when: has_docker_compose_installed is succeeded
      file:
        path: "/home/{{ main_user }}/docker-compose"
        state: directory

    - name: Add script to update all containers in docker-compose config dir
      when: has_docker_compose_installed is succeeded
      copy:
        src: ../files/scripts/docker/update-all-container.sh
        dest: "/home/{{ main_user }}/docker-compose/update-all-containers.sh"
        mode: 0755
