---
- name: 'Docker'
  hosts: all

  roles:
    - role: 'roles/docker'

  tasks:
    - name: 'Copy compose configs'
      when: docker_compose_sync is defined and (docker_compose_sync | length > 0)
      tags: [compose]
      ansible.builtin.copy:
        src: '../files/docker_compose/{{ item }}'
        dest: '{{ docker_compose_dir }}/'
        mode: 0755
      loop: '{{ docker_compose_sync }}'

    - name: 'Sync compose configs'
      when: docker_compose_sync is undefined or (docker_compose_sync | length <= 0)
      tags: [compose]
      ansible.posix.synchronize:
        src: '../files/docker_compose/'
        dest: '{{ docker_compose_dir }}/'

    - name: 'Remove Docker'
      when: false
      become: true
      block:
        - name: 'Remove docker pkgs'
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: absent
        - name: 'Remove images, containers etc.'
          ansible.builtin.file:
            path: '{{ item }}'
            state: absent
          loop:
            - '/var/lib/docker'
            - '/var/lib/containerd'
