# Sets up a fully functional file server
---
- name: 'File server'
  hosts: all

  roles:
    - role: smb
      tags: [smb]
      vars:
        smb_users:
          - username: '{{ main_user }}'
            password:
        smb_dirs:
          # - name:
          #   path:
          #   read_only: false
          #   allow_guest: true

    - role: nfs
      tags: [nfs]
      vars:
        nfs_mounts:
          - src: '{{ synology_nas_host }}:/volume1/media'
            path: 'media'
          - src: '{{ synology_nas_host }}:/volume1/data'
            path: 'data'
