# Sets up a fully functional file server
---
- hosts: all

  roles:
    - name: 'roles/smb'
      tags: [smb]
      vars:
        samba_users:
          - username: '{{ main_user }}'
            password:
        smb_dirs:
          # - name:
          #   path:
          #   read_only: false
          #   allow_guest: true

    - name: 'roles/nfs'
      tags: [nfs]
      vars:
        nfs_mounts:
          - src: '{{ synology_nas_host }}:/volume1/media'
            path: 'media'
          - src: '{{ synology_nas_host }}:/volume1/data'
            path: 'data'
