- hosts: all
  tasks:
    - name: Display distro
      debug:
        msg: "Distro: {{ ansible_distribution }}"

    - name: Create main user
      become: true
      when: main_user != 'pi'
      user:
        name: "{{ main_user }}"
        comment: Create main user
        groups: sudo
        append: true
        password: "{{ password_hash }}"

    - name: Create .ssh directory
      become: true
      when: main_user != 'pi'
      file:
        path: "/home/{{ main_user }}/.ssh"
        state: directory
        owner: "{{ main_user }}"
        group: "{{ main_user }}"

    - name: Copy authorised keys
      become: true
      copy:
        src: ssh_authorized_keys
        dest: "/home/{{ main_user }}/.ssh/authorized_keys"
        owner: "{{ main_user }}"
        group: "{{ main_user }}"

    - name: Make home subdirectories
      file:
        path: "/home/{{ main_user }}/{{ item }}"
        state: directory
        with_items:
          - data
          - dev
          - downloads

    - name: Run common playbook
      include: ./common.yaml

    - name: Run Raspberry Pi playbook
      when: main_user == 'pi'
      include: ./rpi.yaml
