- hosts: all
  tasks:
    - name: "Display distro"
      debug:
        msg: |
          Run this playbook to initialise a new server.
          Ideally it should only be run once. Use the `common` playbook for reprovisioning

          [Machine details]
            Ansible User: {{ ansible_user }}
            User:         {{ main_user }}
            Host:         {{ ansible_host }}
            Distro:       {{ ansible_distribution }}
            Arch:         {{ ansible_architecture }}
    - pause:
        prompt: "Continue ?"

    - set_fact:
        is_rpi_host: "{{ main_user == 'pi' }}"

    - name: "Create main user"
      when: not is_rpi_host
      become: true
      user:
        name: "{{ main_user }}"
        comment: Create main user
        groups: sudo
        append: true
        password: "{{ password_hash }}"

    - name: "Enable passwordless sudo for main user"
      when: not is_rpi_host
      become: true
      lineinfile:
        path: "/etc/sudoers.d/ansible_sudoers"
        mode: 0440
        validate: "visudo -cf %s"
        line: "{{ main_user }} ALL=(ALL) NOPASSWD:ALL"

    - name: "Make home subdirectories"
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: 0755
      loop:
        - data
        - dev
        - downloads
        - drivers

    - name: "Set timezone"
      become: true
      timezone:
        name: Europe/Brussels

- import_playbook: ./common.yaml

- when: is_rpi_host
  import_playbook: ./rpi.yaml
