# You should run this playbook with your root user since it will create the new main
# user to interact and perform plays with.
#
#   e.g $ ansible-playbook playbooks/init_server.yaml -u root
#
# The `temp_pass` var will need to exist in order for the play to execute
---
- hosts: all

  vars:
    # Force the root user
    ansible_user: "{{ 'pi' if is_rpi_host else 'root' }}"

  vars_prompt:
    - name: temp_pass
      prompt: "Password for the new main user"
      private: true

  tasks:
    - name: 'Install sudo'
      when: not is_rpi_host
      become: true
      ansible.builtin.apt:
        name: sudo
        state: latest

    - name: 'Add the non-free repository'
      when: not is_rpi_host
      become: true
      ansible.builtin.replace:
        dest: '/etc/apt/sources.list'
        regexp: '^(deb(?!.* non-free).*)'
        replace: '\1 non-free'

    - name: 'Update apt repo'
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: "Create main user"
      when: not is_rpi_host
      become: true
      ansible.builtin.user:
        name: '{{ main_user }}'
        create_home: true
        password: '{{ temp_pass | password_hash }}'
        append: true
        comment: 'Main User by Ansible'
        shell: /bin/bash
        generate_ssh_key: true
        groups:
          - sudo
          - users
          - systemd-journal

    - name: 'Enable passwordless sudo for main user'
      when: not is_rpi_host
      become: true
      ansible.builtin.lineinfile:
        line: '{{ main_user }} ALL=(ALL) NOPASSWD:ALL'
        mode: 0440
        create: true
        path: '/etc/sudoers.d/ansible_sudoers'
        validate: 'visudo -cf %s'

    - name: 'Include SSH role'
      tags: [ssh]
      ansible.builtin.include_role:
        name: 'roles/ssh'

    - name: 'Ensure capability is correctly set for ping on Proxmox hosts'
      when: "'proxmox' in group_names"
      become: true
      community.general.capabilities:
        path: '/bin/ping'
        capability: cap_net_raw+p
        state: present

    - name: 'Display success prompt'
      ansible.builtin.pause:
        seconds: 1
        prompt: |
          ==============================================================================
            Server initialized!

            It's not recommended to run this playbook more than once against a server.
            Continue with setup_server.yaml and common.yaml to configure the server for
            the new main user '{{ main_user }}'
          ==============================================================================
