---
- hosts: all
  tasks:
    - name: 'Check if host is a Raspberry Pi'
      set_fact:
        is_rpi_host: "{{ main_user == 'pi' }}"

    - name: "Create main user"
      when: not is_rpi_host
      become: true
      user:
        append: true
        comment: Create main user
        groups: sudo
        name: '{{ main_user }}'
        password: '{{ password_hash }}'

    - name: 'Enable passwordless sudo for main user'
      when: not is_rpi_host
      become: true
      lineinfile:
        line: '{{ main_user }} ALL=(ALL) NOPASSWD:ALL'
        mode: 0440
        path: '/etc/sudoers.d/ansible_sudoers'
        validate: 'visudo -cf %s'

    - name: 'Make home subdirectories'
      file:
        mode: 0755
        path: '{{ ansible_env.HOME }}/{{ item }}'
        state: directory
      loop:
        - data
        - dev
        - downloads
        - drivers

    - name: 'Set timezone'
      become: true
      timezone:
        name: Europe/Brussels

- import_playbook: './common.yaml'

- import_playbook: './rpi.yaml'
  when: is_rpi_host
