- hosts: all
  tasks:
    - name: Display distro
      debug:
        msg: "Distro: {{ ansible_distribution }}"

    - name: Create main user
      become: true
      when: main_user != 'pi'
      user:
        name: "{{ main_user }}"
        comment: Create main user
        groups: sudo
        append: true
        password: "{{ password_hash }}"

    - name: Enable passwordless sudo for main user
      become: true
      when: main_user != 'pi'
      lineinfile:
        path: "/etc/sudoers.d/ansible_sudoers"
        mode: 0440
        validate: "visudo -cf %s"
        line: "{{ main_user }} ALL=(ALL) NOPASSWD:ALL"
    - name: Make home subdirectories
      file:
        path: "/home/{{ main_user }}/{{ item }}"
        state: directory
      loop:
        - data
        - dev
        - downloads

    - name: Run common playbook
      include: ./common.yaml

    - name: Run Raspberry Pi playbook
      when: main_user == 'pi'
      include: ./rpi.yaml
