# Sets up headless monitoring across hosts
#
# NOTE: on macOS you might need to set the follow env: OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
#       when the cloudalchemy.node_exporter is included in a play
#       see https://github.com/cloudalchemy/ansible-node-exporter/issues/168
---
- name: 'Monitoring'

  hosts: all

  vars_prompt:
    - name: influxdb_token
      prompt: "InfluxDB Token (v2)"
      private: true
    - name: loki_host
      prompt: "Loki host (IP + port)"

  roles:
    - role: cloudalchemy.node_exporter
      tags: [prometheus]

    - role: telegraf
      tags: [telegraf]
      vars:
        synology_nas_host: # noqa: var-naming[no-role-prefix]

    - role: glances
      tags: [glances]

    - role: patrickjahns.promtail
      tags: [promtail]
      vars:
        promtail_version: latest
        promtail_loki_server_url: '{{ loki_host }}'
        promtail_config_dir: '/opt/promtail'
        promtail_positions_directory: '/tmp'
        promtail_config_server:
          http_listen_port: 9080
          grpc_listen_port: 9081
        promtail_config_clients:
          - url: 'http://{{ promtail_loki_server_url }}/loki/api/v1/push'
            external_labels:
              host: '{{ ansible_hostname }}'
        promtail_config_scrape_configs:
          - job_name: system
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: varlogs
                  __path__: '/var/log/*log'
