---
- hosts: rpi

  tasks:
    - name: 'Setup 3.5 TFT touch display'
      ansible.builtin.include_tasks: 'tasks/rpi/mhs-3.5-inch-display.yaml'

    - name: 'OctoDash'
      ansible.builtin.include_role:
        name: 'roles/octodash'
