---
- hosts: [pihole-lxc]

  tasks:
    - name: 'Check if pihole is available'
      ansible.builtin.shell: 'command -v pihole'

    - name: 'Enable automatic backup'
      ansible.builtin.cron:
        name: 'Automatic pihole backup'
        minute: '00'
        hour: '10'
        day: '*'
        month: '*'
        weekday: '*/7'
        command: 'pihole -a -t bak.tar.gz'
        user: '{{ main_user }}'
        jobname: 'pihole-auto-backup'
        state: present

    - name: 'Setup Prometheus exporter'
      tags: [prometheus]
      ansible.builtin.include_role:
        name: 'roles/pihole_exporter'
      vars:
        pihole_hostname: 'localhost'
        pihole_port: '80'
        pihole_api_token: '8c341d2a6607f23b893f41475ed7fb6f035fc96a8bbc6c585ac8d9dfb04dc3d5'


# https://github.com/vmstan/gravity-sync/wiki/Installing
