# Run this after initializing a server with init_server.yaml
---
- hosts: all

  roles:
    - 'roles/motd'

  tasks:
    - name: 'Make home subdirectories'
      ansible.builtin.file:
        mode: 0755
        path: '{{ ansible_env.HOME }}/{{ item }}'
        state: directory
      loop:
        - .config
        - data
        - dev
        - downloads
        - drivers

    - name: 'Include ZSH role'
      ansible.builtin.include_role:
        name: 'roles/zsh'

    - name: 'Include Starship role'
      ansible.builtin.include_role:
        name: 'roles/starship'
