# Run this after initializing a server with init_server.yaml
---
- name: 'Setup server'
  hosts: all

  roles:
    - role: shell
      tags: [shell]
    - role: motd
      tags: [motd]
    - role: logrotate
      tags: [logs]
    - role: tmux
      tags: [tmux]
    - role: python
      tags: [python]
    - role: duf
      tags: [duf]
    - role: croc
      tags: [croc]

  tasks:
    - name: 'Make home subdirectories'
      ansible.builtin.file:
        mode: 0755
        path: '{{ ansible_env.HOME }}/{{ item }}'
        state: directory
      loop:
        - data
        - dev
        - downloads
        - drivers

    - name: 'Include ZSH role'
      ansible.builtin.include_role:
        name: zsh

    - name: 'Include Starship role'
      ansible.builtin.include_role:
        name: starship
