# Run this after initializing a server with init_server.yaml
---
- name: 'Setup server'
  hosts: all

  roles:
    - role: 'roles/shell'
      tags: [shell]
    - role: 'roles/motd'
      tags: [motd]
    - role: 'roles/logrotate'
      tags: [logs]
    - role: 'roles/tmux'
      tags: [tmux]
    - role: 'roles/python'
      tags: [python]
    - role: 'roles/duf'
      tags: [duf]

  tasks:
    - name: 'Make home subdirectories'
      ansible.builtin.file:
        mode: 0755
        path: '{{ ansible_env.HOME }}/{{ item }}'
        state: directory
      loop:
        - data
        - dev
        - downloads
        - drivers

    - name: 'Include ZSH role'
      ansible.builtin.include_role:
        name: 'roles/zsh'

    - name: 'Include Starship role'
      ansible.builtin.include_role:
        name: 'roles/starship'
