- hosts: all
  become: true

  vars_prompt:
    - name: sshd_port
      prompt: "Port to use for sshd"
      default: "{{ 9000 | random(start=2000) }}"

  tasks:
    - name: Create .ssh directory
      file:
        path: "/home/{{ main_user }}/.ssh"
        state: directory
        owner: "{{ main_user }}"
        group: "{{ main_user }}"

    - name: Copy authorised keys
      copy:
        src: ../files/ssh_authorized_keys
        dest: "/home/{{ main_user }}/.ssh/authorized_keys"
        owner: "{{ main_user }}"
        group: "{{ main_user }}"

    - name: Copy sshd config
      template:
        src: ../templates/system/etc/ssh/sshd_config.j2
        dest: /etc/ssh/sshd_config

    - name: Restart SSH service (sshd)
      systemd:
        name: sshd
        state: restarted
