# Playbook to setup a syslog server
---
- hosts: [proxmox, rpi, vms]

  roles:
    - name: 'roles/logrotate'
      tags: [logs]
    - name: 'roles/rsyslog'
      tags: [rsyslog]
      vars:
        rsyslog_templates: []

  tasks:
    - name: 'Disable kernel logging for LXC'
      when: "'proxmox' in group_names"
      ansible.builtin.replace:
        dest: '/etc/rsyslog.conf'
        regexp: '^module\(load="imklog"\)$'
        replace: '#module(load="imklog")'
