- hosts: all
  serial: 2
  tasks:
    - name: Upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: true

    - register: docker_compose_upgrade_script
      stat:
        path: "{{ ansible_env.HOME }}/docker-compose/update-all-containers.sh"

    - name: Upgrade docker-compose containers
      when: docker_compose_upgrade_script.stat.exists and docker_compose_upgrade_script.stat.executable
      shell: "./update-all-containers.sh"
      args:
        chdir: "{{ ansible_env.HOME }}/docker-compose"
