- hosts: all

  serial: 2

  tasks:
    - name: 'Upgrade apt packages'
      tags: [apt]
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: 'Upgrade docker-compose configs'
      tags: [docker]
      block:
        - name: 'Check if upgrade script exists'
          register: docker_compose_upgrade_script
          ansible.builtin.stat:
            path: '{{ docker_compose_dir }}/update-all-containers.sh'

        - name: 'Upgrade docker-compose containers'
          when:
            - docker_compose_upgrade_script.stat.exists
            - docker_compose_upgrade_script.stat.executable
          changed_when: true
          ansible.builtin.command: './update-all-containers.sh'
          args:
            chdir: '{{ docker_compose_dir }}'
