# Ref: https://linuxize.com/post/how-to-install-and-configure-vnc-on-ubuntu-20-04/
---
- hosts: all
  tasks:
    - name: "Install required VNC packages"
      apt:
        name:
          - xfce4
          - xfce4-goodies
          - tigervnc-standalone-server

    - name: "Setup VNC password"
      command: vncpasswd

    - name: "Configure TigerVNC to use XFCE"
      blockinfile:
        create: true
        mode: 0744
        path: "{{ ansible_env.HOME }}/.vnc/xstartup"
        block: |
          #!/bin/sh
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          exec startxfce4

    - name: "Create TigerVNC config file"
      blockinfile:
        create: true
        path: "{{ ansible_env.HOME }}/.vnc/config"
        block: |
          geometry=1024x600
          dpi=96

    - name: "Create systemd unit"
      become: true
      blockinfile:
        create: true
        path: "/etc/systemd/system/vncserver@.service"
        block: |
          [Unit]
          Description=TigerVNC Remote desktop service (VNC)
          After=syslog.target network.target

          [Service]
          Type=simple
          User={{ main_user }}
          PAMName=login
          PIDFile=/home/%u/.vnc/%H%i.pid
          ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill :%i > /dev/null 2>&1 || :'
          ExecStart=/usr/bin/vncserver :%i -geometry 1440x900 -alwaysshared -fg
          ExecStop=/usr/bin/vncserver -kill :%i

          [Install]
          WantedBy=multi-user.target

    - name: "Enable systemd unit"
      become: true
      shell: |
        systemctl daemon-reload
        systemctl enable vncserver@1.service

    - name: "Restart telegraf.service"
      become: true
      systemd:
        name: vncserver@1
        state: restarted
