services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    env_file: radarr.env
    ports:
      - 7878:7878
    volumes:
      - ./config:/config
      - /movies:/movies
      - /downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  radarr_exporter:
    image: ghcr.io/onedr0p/exportarr
    container_name: radarr_exporter
    env_file: radarr_exporter.env
    ports:
      - 9708:9708
    command: ['radarr']
    restart: unless-stopped
