version: '3'

services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    env_file: radarr.env
    ports:
      - 7878:7878
    volumes:
      - ./config:/config
      - /movies:/movies
      - /downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
