- name: 'Install APT HTTPS transport'
  become: true
  tags: [apt]
  ansible.builtin.apt:
    name: 'apt-transport-https'
    state: present

- name: 'Download Telegraf apt key'
  become: true
  tags: [apt]
  ansible.builtin.apt_key:
    url: 'https://repos.influxdata.com/influxdb.key'
    id: 2582E0C5
    state: present

- name: 'Add Telegraf repository'
  become: true
  tags: [apt]
  ansible.builtin.apt_repository:
    # yamllint disable-line rule:line-length
    repo: 'deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
    filename: telegraf
    state: present

- name: 'Install Telegraf apt package'
  become: true
  tags: [apt]
  ansible.builtin.apt:
    name: telegraf
    state: latest
    update_cache: true

- name: 'Copy config directory'
  become: true
  tags: [config]
  ansible.builtin.synchronize:
    src: '../files/config_dir/'
    dest: '{{ telegraf_dir }}'

- name: 'Copy template files to config dir'
  become: true
  tags: [config]
  ansible.builtin.template:
    src: '{{ item }}'
    dest: "{{ telegraf_dir }}/telegraf.d/{{ item | basename | regex_replace('.j2','') }}"
    mode: 0644
  with_fileglob: '../templates/*.j2'

- name: 'Remove SMART config when no devices monitored'
  when: telegraf_smart_devices | length == 0
  become: true
  tags: [config]
  ansible.builtin.file:
    path: '{{ telegraf_dir }}/telegraf.d/inputs.smart.conf'
    state: absent

- name: 'Copy main telegraf.conf'
  become: true
  tags: [config]
  ansible.builtin.template:
    src: 'templates/telegraf.conf.j2'
    dest: "{{ telegraf_dir }}/telegraf.conf"
    mode: 0644

- name: 'Include custom config tasks'
  ansible.builtin.include_tasks: './custom_config.yaml'

- name: 'Include docker tasks'
  ansible.builtin.include_tasks: './docker.yaml'

- name: 'Include SNMP tasks'
  tags: [snmp]
  ansible.builtin.include_tasks: './snmp.yaml'

- name: 'Restart telegraf'
  notify: restart_telegraf
  ansible.builtin.command: /bin/true
  changed_when: false
