- name: 'Install snmp tools'
  become: true
  tags: [apt]
  ansible.builtin.apt:
    name:
      - snmp
      - snmp-mibs-downloader # requires non-free repo
    state: present

- name: 'Synology SNMP'
  tags: [synology, mibs]
  block:
    - name: 'Download Synology mibs'
      become: true
      ansible.builtin.unarchive:
        src: 'https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_MIB_File.zip'
        dest: '{{ telegraf_snmp_mibs_dir }}/'
        remote_src: true
    - name: 'Move Synology mibs to correct dir'
      become: true
      changed_when: true
      ansible.builtin.shell: 'mv *.txt {{ telegraf_snmp_mibs_dir }}/'
      args:
        chdir: '{{ telegraf_snmp_mibs_dir }}/Synology_MIB_File'
    - name: 'Remove stale folder'
      become: true
      ansible.builtin.file:
        path: '{{ telegraf_snmp_mibs_dir }}/Synology_MIB_File'
        state: absent

- name: 'Download base mibs'
  become: true
  tags: [mibs]
  changed_when: true
  ansible.builtin.command: 'download-mibs'
