name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: 'Install runtimes (asdf)'
        uses: asdf-vm/actions/install@v1

      - name: 'Install dependencies'
        run: make dependencies

      - name: 'Lint: Ansible + YAML'
        run: make lint

      - name: 'Stub 1Password CLI (op)'
        run: |
          echo "exit 0" > /usr/local/bin/op
          chmod +x /usr/local/bin/op

      - name: "Lint extra files"
        uses: github/super-linter@main
        env:
          VALIDATE_ANSIBLE: false
          VALIDATE_YAML: false
          VALIDATE_GO: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_ENV: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
