name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Set up Python"
        uses: actions/setup-python@master
        with:
          python-version: 3.9.0

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          make dependencies

      - name: "Lint Ansible files"
        run: make lint

      - name: "Lint extra files"
        uses: github/super-linter@main
        env:
          VALIDATE_ANSIBLE: false
          VALIDATE_YAML: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_ENV: true
          VALIDATE_GO: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
