name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
